# Smart Pandoc Debugger Pre-commit Configuration
# This replaces the massive custom git hook with a proper, maintainable setup

repos:
  # Code formatting and style
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-merge-conflict
      - id: check-added-large-files

  # Python specific checks
  - repo: https://github.com/psf/black
    rev: 23.9.1
    hooks:
      - id: black
        args: [--line-length=100]

  - repo: https://github.com/pycqa/flake8
    rev: 6.1.0
    hooks:
      - id: flake8

  # Custom project-specific hooks
  - repo: local
    hooks:
      # Protect roadmap files
      - id: protect-roadmap
        name: Protect roadmap files
        entry: scripts/hooks/protect-roadmap.py
        language: python
        files: ^docs/roadmap/
        always_run: false

      # Check file size limits for modularity
      - id: check-file-size
        name: Check file size limits (enforce modularity)
        entry: scripts/hooks/check-file-size.py
        language: python
        files: \.py$
        args: [--max-total-lines=300, --max-code-lines=200]

      # Prevent alternative-debugger imports
      - id: no-alternative-imports
        name: Prevent alternative-debugger imports
        entry: scripts/hooks/check-alternative-imports.py
        language: python
        files: \.py$

      # Note: Tier 1 tests disabled in pre-commit since pytest environment is complex
      # Run tests manually with: pytest tests/unit/test_error_finder_consolidated.py -m tier1 -v
